DROP DATABASE IF EXISTS SCHOOL;
CREATE DATABASE SCHOOL;
USE SCHOOL;

CREATE TABLE SUBJECTS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    SUBJECT_NAME VARCHAR(20) NOT NULL,
    FIRST_SEMESTER INT NOT NULL,
    SECOND_SEMESTER INT NOT NULL,
    ANNUAL_ASSESSMENT INT NOT NULL
);

SET SQL_SAFE_UPDATES=0;

INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("Math",6,6,6);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("BEL",6,5,5);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("History",5,6,6);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("Geography",6,6,6);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("Programing",6,6,6);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("English",5,4,5);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("OOP",6,6,6);
INSERT INTO SUBJECTS(SUBJECT_NAME, FIRST_SEMESTER,SECOND_SEMESTER,ANNUAL_ASSESSMENT) VALUES("ANALOGUE",5,5,5);

SELECT *FROM SUBJECTS;

DROP TABLE SUBJECTS;
DROP DATABASE SCHOOL;

