DROP DATABASE IF EXISTS MYDATABASE;
CREATE DATABASE MYDATABASE;
USE MYDATABASE;


CREATE TABLE Person(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    DESCR VARCHAR(35) NOT NULL,
    GENDER VARCHAR(7) NOT NULL,
    SHOE_SIZE INT NOT NULL,
    PANTS_SIZE VARCHAR(3) NOT NULL,
    SHIRT_SIZE VARCHAR(3) NOT NULL,
    PHONE_BRAND VARCHAR(30) NOT NULL
);

SET SQL_SAFE_UPDATES=0;

INSERT INTO Person(NAME, AGE,DESCR,GENDER,SHOE_SIZE,PANTS_SIZE, SHIRT_SIZE, PHONE_BRAND) VALUES("Kaloyan",17,"COOL","male",42,"M","M","Samsung");
INSERT INTO Person(NAME, AGE,DESCR,GENDER,SHOE_SIZE,PANTS_SIZE, SHIRT_SIZE, PHONE_BRAND) VALUES("Mitko",18,"COOL","male",43,"M","M","IPhone");
INSERT INTO Person(NAME, AGE,DESCR,GENDER,SHOE_SIZE,PANTS_SIZE, SHIRT_SIZE, PHONE_BRAND) VALUES("Vikctoria",20,"COOL","female",38,"S","XS","Samsung");
INSERT INTO Person(NAME, AGE,DESCR,GENDER,SHOE_SIZE,PANTS_SIZE, SHIRT_SIZE, PHONE_BRAND) VALUES("Rumen",16,"COOL","male",44,"M","M","Samsung");

SELECT *FROM Person;

SELECT *FROM Person
WHERE SHOE_SIZE = 43 AND NOT AGE = 20;

SELECT *FROM Person
ORDER BY AGE;


UPDATE  Person
SET SHOE_SIZE=50
WHERE ID=4;
SELECT *FROM Person;

DELETE FROM Person;
SELECT *FROM Person;

DROP TABLE Person;

DROP DATABASE MYDATABASE;